export const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || "https://www.servicell.com.ar").replace(/\/$/, "");
export const services = [
  { slug: "cambio-modulo", name: "Cambio de módulo", short: "Módulo y pantalla", icon: "▣", problem: "Se rompió la pantalla", symptom: "Vidrio quebrado, manchas, líneas o una pantalla que no responde al tacto.", when: "Si la imagen se ve mal o el táctil falla, consultá antes de seguir usando el equipo para evitar más daños." },
  { slug: "cambio-pantalla", name: "Cambio de pantalla", short: "Pantalla", icon: "◫", problem: "Se rompió la pantalla", symptom: "Fisuras, zonas sin imagen, parpadeos o fallas en la respuesta táctil.", when: "La reparación adecuada depende del modelo y del tipo de pantalla del equipo." },
  { slug: "cambio-bateria", name: "Cambio de batería", short: "Batería", icon: "▰", problem: "La batería dura poco", symptom: "La carga dura menos, el teléfono se apaga sin aviso o la batería se descarga rápidamente.", when: "Una revisión permite diferenciar una batería gastada de un problema de carga o software." },
  { slug: "pin-de-carga", name: "Pin o puerto de carga", short: "Puerto de carga", icon: "⌁", problem: "No carga", symptom: "El cable se desconecta, el teléfono carga de forma intermitente o no reconoce el cargador.", when: "No fuerces el conector: primero conviene revisar puerto, cable y circuito de carga." },
  { slug: "reparacion-iphone", name: "Reparación de iPhone", short: "iPhone", icon: "◉", problem: "Otro problema", symptom: "Consultas por pantalla, batería, carga y otras fallas en equipos iPhone.", when: "Contanos el modelo y qué sucede para orientarte sobre el diagnóstico." },
  { slug: "reparacion-samsung", name: "Reparación de Samsung", short: "Samsung", icon: "◈", problem: "Otro problema", symptom: "Consultas por pantalla, batería, carga y otras fallas en equipos Samsung.", when: "La disponibilidad y el tipo de reparación dependen del modelo." },
  { slug: "celular-no-carga", name: "Celular que no carga", short: "Falla de carga", icon: "ϟ", problem: "No carga", symptom: "No carga, tarda demasiado o solo funciona al mover el cable.", when: "La causa puede ser el puerto, el cargador, la batería o el circuito: requiere revisión." },
  { slug: "celular-mojado", name: "Celular mojado", short: "Daño por líquido", icon: "◌", problem: "Se mojó", symptom: "El teléfono tuvo contacto con agua u otro líquido y ahora presenta fallas.", when: "Apagalo y no lo conectes al cargador. Consultanos para saber cómo proceder." },
];
export type CityKey = "la-rioja" | "san-juan";
export const cities: Record<CityKey, {name:string; capital:string; heading:string; eyebrow:string; intro:string; area:string; whatsapp:string; phone:string; address:string; hours:string; maps:string; local:string; latitude:string; longitude:string; entityId:string}> = {
  "la-rioja": { name:"La Rioja", capital:"La Rioja Capital", heading:"Reparación de celulares en La Rioja", eyebrow:"SERVICIO TÉCNICO · LA RIOJA CAPITAL", intro:"Servicio técnico para iPhone, Samsung y otras marcas. Pantallas, baterías, conectores de carga y más.", area:"La Rioja Capital", whatsapp:process.env.NEXT_PUBLIC_LA_RIOJA_WHATSAPP || "", phone:process.env.NEXT_PUBLIC_LA_RIOJA_PHONE || "", address:process.env.NEXT_PUBLIC_LA_RIOJA_ADDRESS || "", hours:process.env.NEXT_PUBLIC_LA_RIOJA_HOURS || "", maps:process.env.NEXT_PUBLIC_LA_RIOJA_MAPS_URL || "https://maps.app.goo.gl/5jaxo58WuGtaQr566", local:"Consultá por reparaciones en La Rioja Capital. Contanos la marca, el modelo y la falla para recibir orientación sobre los próximos pasos.", latitude:"-29.4147563", longitude:"-66.8580253", entityId:`${siteUrl}/#servicell-la-rioja` },
  "san-juan": { name:"San Juan", capital:"San Juan Capital", heading:"Reparación de celulares en San Juan", eyebrow:"SERVICIO TÉCNICO · SAN JUAN CAPITAL", intro:"¿Tu celular necesita reparación? Consultá por pantallas, baterías, carga y fallas de iPhone, Samsung y otras marcas.", area:"San Juan Capital", whatsapp:process.env.NEXT_PUBLIC_SAN_JUAN_WHATSAPP || "", phone:process.env.NEXT_PUBLIC_SAN_JUAN_PHONE || "", address:process.env.NEXT_PUBLIC_SAN_JUAN_ADDRESS || "", hours:process.env.NEXT_PUBLIC_SAN_JUAN_HOURS || "", maps:process.env.NEXT_PUBLIC_SAN_JUAN_MAPS_URL || "https://maps.app.goo.gl/AyEWdTqiTQ26XTW96", local:"Atención de consultas para San Juan Capital. Describí qué le ocurre a tu equipo y te ayudaremos a identificar una posible revisión.", latitude:"-31.5833507", longitude:"-68.5252575", entityId:`${siteUrl}/#servicell-san-juan` },
};
export const brandEntityId = `${siteUrl}/#servicell`;
export const serviceTitle:Record<string,string>={"cambio-modulo":"Cambio de módulo","cambio-pantalla":"Cambio de pantalla","cambio-bateria":"Cambio de batería de celular","pin-de-carga":"Reparación del pin de carga","reparacion-iphone":"Reparación de iPhone","reparacion-samsung":"Reparación de Samsung","celular-no-carga":"Reparación de celular que no carga","celular-mojado":"Reparación de celular mojado"};
export function serviceFaq(slug:string,city:CityKey){const c=cities[city];const common=[{question:`¿Dónde reparar un celular en ${c.name}?`,answer:`Podés consultar a Servicell por reparaciones en ${c.capital}. Contanos la marca, el modelo y qué falla presenta para recibir orientación. La dirección y los horarios se publicarán cuando estén confirmados.`}];const bySlug:Record<string,{question:string;answer:string}[]>={
  "cambio-bateria":[{question:`¿Dónde cambiar la batería de un iPhone en ${c.name}?`,answer:`Consultá a Servicell por cambio de batería de iPhone en ${c.capital}. Indicá el modelo y los síntomas; la compatibilidad y las opciones se revisan para cada equipo.`},{question:"¿Cuándo conviene cambiar la batería?",answer:"Puede convenir revisarla cuando dura mucho menos, el equipo se apaga inesperadamente o la carga baja rápido. Una revisión ayuda a distinguir el desgaste de una falla del cargador, el puerto o el software."}],
  "cambio-modulo":[{question:"¿Se puede reparar una pantalla rota?",answer:"Se puede evaluar la reparación cuando el vidrio está quebrado, hay manchas o líneas, o el táctil dejó de responder. La alternativa depende del modelo y del daño; consultá con marca y modelo."}],
  "cambio-pantalla":[{question:"¿Se puede reparar una pantalla rota?",answer:"Sí, se puede consultar por una pantalla rota, con imagen dañada o con fallas táctiles. La reparación y el componente adecuado dependen del modelo y de la revisión del equipo."}],
  "celular-no-carga":[{question:"¿Por qué mi celular no carga?",answer:"Puede deberse al cable o cargador, suciedad o daño en el puerto, la batería o el circuito de carga. No fuerces el conector; probá un cable confiable y consultá si la falla continúa."}],
  "pin-de-carga":[{question:"¿Por qué mi celular no carga?",answer:"Un puerto flojo o dañado es una posibilidad, aunque también puede ser el cable, el cargador, la batería o el circuito. La revisión permite identificar la causa antes de definir una reparación."}],
  "celular-mojado":[{question:"¿Se puede reparar un celular mojado?",answer:"A veces es posible, pero depende del líquido, el tiempo transcurrido y los daños internos. Apagalo, no lo cargues ni intentes secarlo con calor y consultá para recibir indicaciones."}],
};return [...common,...(bySlug[slug]||[{question:`¿Qué modelos atienden para ${serviceTitle[slug]?.toLowerCase()||"esta reparación"}?`,answer:"Podés consultar por iPhone, Samsung y otras marcas. Compartí el modelo para revisar qué opciones corresponden a tu equipo."}])];}
export function whatsappUrl(city:CityKey, message:string) { const number=cities[city].whatsapp.replace(/\D/g,""); return number ? `https://wa.me/${number}?text=${encodeURIComponent(message)}` : ""; }
export const defaultMessage = (city:CityKey, service?:string) => `Hola Servicell, quiero consultar por ${service || "una reparación"} en ${cities[city].capital}. Mi celular es:`;
export function serviceCityFor(slug:string) { return services.find(s=>s.slug===slug); }
